### ISSUE TITLE
The preview isnt working

### ISSUE THREAD

**Issue by Dorfeuheinz** [ddorstijn-usoft/squire-editor#1]
Good day.
Just wanted to inform that the preview isnt working. None of the buttons are actually implementing the style on the text. Hoped you could kindly look into it.
Thanks

Awesome project btw. Love you

**Comment by ddorstijn** [comment]
Hey,

I opened this as showcase for an [issue](https://github.com/fastmail/Squire/issues/446) in Squire. Basically, when the webcomponent is moved in the document tree, it doesn't properly reference it no more. I will remove the test code in the HTML file where it moves the component after some time.

**Comment by Dorfeuheinz** [comment]
oh ok, got it. thanks anyway. it looks great
